name: remote-deploy
description: Rsync Hugo public assets to a remote host and trigger the deploy script.
inputs:
  deploy-key:
    description: Private SSH key for deploy@ host
    required: true
  deploy-host:
    description: SSH host
    required: true
  remote-path:
    description: Remote directory to sync into (e.g., preview/hugo-cicd-example/)
    required: true
  deploy-environment:
    description: Environment argument passed to remote deploy script (preview/prod)
    required: true
runs:
  using: "composite"
  steps:
    - name: Prepare SSH credentials
      shell: bash
      env:
        DEPLOY_KEY: ${{ inputs.deploy-key }}
        DEPLOY_HOST: ${{ inputs.deploy-host }}
      run: |
        install -m 700 -d ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_deploy
        chmod 600 ~/.ssh/id_deploy
        ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
    - name: Sync artifacts
      shell: bash
      env:
        DEPLOY_HOST: ${{ inputs.deploy-host }}
        REMOTE_PATH: ${{ inputs.remote-path }}
      run: |
        rsync -avz --delete -e "ssh -i ~/.ssh/id_deploy" public/ "deploy@${DEPLOY_HOST}:${REMOTE_PATH}"
    - name: Trigger deploy script
      shell: bash
      env:
        DEPLOY_HOST: ${{ inputs.deploy-host }}
        DEPLOY_ENV: ${{ inputs.deploy-environment }}
      run: |
        ssh -i ~/.ssh/id_deploy "deploy@${DEPLOY_HOST}" deploy hugo-cicd-example "$DEPLOY_ENV"
